name: My First Pipeline
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t ci-practice-app .
      - name: run docker image
        run: docker run ci-practice-app
