name: My First Pipeline
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build docker image
        run: docker build -t ci-practice-app .
      - name: run docker image
        run: docker run ci-practice-app
      - name: Show that secret is available
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}
        run: echo "The key starts with: ${API_KEY:0:5}"